### PR TITLE
Refactor SSHA and SHA comparators

### PR DESCRIPTION
**Pull request by hugotiburtino**
And resolve conflicts from the ory/kratos master branch.

### CODE REVIEW

**Comment by zambien** [comment]
@hugotiburtino thanks for the additional commits.  I merged then reverted this PR.  There are too many changes and I would not want to burden the kratos developers with reviewing them all.  If you want to add more changes, please only change things related to the features we've been discussing, otherwise I'm certain the developers on the kratos side will reject the PR.  Thank you!

**Comment by hugotiburtino** [comment]
Hi @zambien , sorry about that, I'll do as you say.

**Comment by zambien** [comment]
> Hi @zambien , sorry about that, I'll do as you say.

Thanks @hugotiburtino, much appreciated!  If I can help please let me know!

**Comment by hugotiburtino** [comment]
I hope #5 is acceptable. I'm not sure of what caused so much changes, maybe you want to tackle the conflict problems and see if you can avoid the unwanted changes. I suppose the people of Ory will ask you to do it

**Pull request merged**
